batch_size: 256
entity_class_num: 133
entity_label:
  '0': O
  '1': B-Airport
  '10': I-Chatting
  '100': I-Relative_Month_Future_2
  '101': B-Relative_Month_Past_1
  '102': I-Relative_Month_Past_1
  '103': B-Relative_Month_Past_2
  '104': I-Relative_Month_Past_2
  '105': B-Relative_Month_Present
  '106': I-Relative_Month_Present
  '107': B-Relative_Week_Future_1
  '108': I-Relative_Week_Future_1
  '109': B-Relative_Week_Future_2
  '11': B-City
  '110': I-Relative_Week_Future_2
  '111': B-Relative_Week_Present
  '112': I-Relative_Week_Present
  '113': B-Relative_Year_Present
  '114': I-Relative_Year_Present
  '115': B-Roaming
  '116': I-Roaming
  '117': B-RoamingPlan
  '118': I-RoamingPlan
  '119': B-RoamingPlan_Hi
  '12': I-City
  '120': I-RoamingPlan_Hi
  '121': B-Roaming_Announce
  '122': I-Roaming_Announce
  '123': B-Stay_Period
  '124': I-Stay_Period
  '125': B-TextMsg
  '126': I-TextMsg
  '127': B-VideoCall
  '128': I-VideoCall
  '129': B-VoiceCall
  '13': B-Contents_Payment
  '130': I-VoiceCall
  '131': B-VoiceCall_Block
  '132': I-VoiceCall_Block
  '14': I-Contents_Payment
  '15': B-Continent
  '16': I-Continent
  '17': B-Count_Month
  '18': I-Count_Month
  '19': B-Country
  '2': I-Airport
  '20': I-Country
  '21': B-Coupon_Gift
  '22': I-Coupon_Gift
  '23': B-Coupon_LongTerm
  '24': I-Coupon_LongTerm
  '25': B-Data
  '26': I-Data
  '27': B-Data_Block
  '28': I-Data_Block
  '29': B-Data_Size
  '3': B-Airport_Terminal
  '30': I-Data_Size
  '31': B-Date
  '32': I-Date
  '33': B-Every_Month
  '34': I-Every_Month
  '35': B-LocalTime_Announce
  '36': I-LocalTime_Announce
  '37': B-Membership_Gold
  '38': I-Membership_Gold
  '39': B-Membership_Silver
  '4': I-Airport_Terminal
  '40': I-Membership_Silver
  '41': B-Membership_VIP
  '42': I-Membership_VIP
  '43': B-Micro_Payment
  '44': I-Micro_Payment
  '45': B-Mobile
  '46': I-Mobile
  '47': B-Month
  '48': I-Month
  '49': B-Partner_Bakery
  '5': B-Average
  '50': I-Partner_Bakery
  '51': B-Partner_CVS
  '52': I-Partner_CVS
  '53': B-Partner_Cafe
  '54': I-Partner_Cafe
  '55': B-Partner_Edu
  '56': I-Partner_Edu
  '57': B-Partner_Fashion
  '58': I-Partner_Fashion
  '59': B-Partner_Finance
  '6': I-Average
  '60': I-Partner_Finance
  '61': B-Partner_Life
  '62': I-Partner_Life
  '63': B-Partner_Media
  '64': I-Partner_Media
  '65': B-Partner_Movie
  '66': I-Partner_Movie
  '67': B-Partner_Pizza
  '68': I-Partner_Pizza
  '69': B-Partner_Restaurant
  '7': B-Average_Month
  '70': I-Partner_Restaurant
  '71': B-Partner_Shopping
  '72': I-Partner_Shopping
  '73': B-Partner_Sports
  '74': I-Partner_Sports
  '75': B-Partner_ThemePark
  '76': I-Partner_ThemePark
  '77': B-Partner_Travel
  '78': I-Partner_Travel
  '79': B-Payment_Billed
  '8': I-Average_Month
  '80': I-Payment_Billed
  '81': B-Payment_Unpaid
  '82': I-Payment_Unpaid
  '83': B-Payment_Used
  '84': I-Payment_Used
  '85': B-PhoneNumber
  '86': I-PhoneNumber
  '87': B-Plans
  '88': I-Plans
  '89': B-Present
  '9': B-Chatting
  '90': I-Present
  '91': B-Relative_Date_Future_1
  '92': I-Relative_Date_Future_1
  '93': B-Relative_Date_Future_2
  '94': I-Relative_Date_Future_2
  '95': B-Relative_Date_Present
  '96': I-Relative_Date_Present
  '97': B-Relative_Month_Future_1
  '98': I-Relative_Month_Future_1
  '99': B-Relative_Month_Future_2
entity_optimizer_lr: 4.0e-05
file_path: ./nlu.md
gpu_num: 1
intent_class_num: 89
intent_label:
  '0': intent_OOD
  '1': "intent_T\uB85C\uBC0D_\uC74C\uC131\uC218\uBC1C\uC2E0\uCC28\uB2E8_\uAC00\uC785"
  '10': "intent_T\uBA64\uBC84\uC2ED_\uAC00\uC785_\uC624\uB958_\uBB38\uC758_FAQ"
  '11': "intent_T\uBA64\uBC84\uC2ED_\uB4F1\uAE09_\uAE30\uC900_\uBB38\uC758_FAQ"
  '12': "intent_T\uBA64\uBC84\uC2ED_\uC0AC\uC6A9\uCC98_\uBB38\uC758_FAQ"
  '13': "intent_T\uBA64\uBC84\uC2ED_\uC0AC\uC6A9\uCC98_\uC774\uC6A9_\uBB38\uC758_FAQ"
  '14': "intent_\uAE30\uBCF8_\uB3C4\uC6C0\uB9D0_\uBB38\uC758"
  '15': "intent_\uB0B4_\uBD80\uAC00\uC11C\uBE44\uC2A4_\uBB38\uC758"
  '16': "intent_\uB0B4_\uC694\uAE08\uC81C_\uBB38\uC758"
  '17': "intent_\uB0B4\uB9D8\uB300\uB85C\uD50C\uB7EC\uC2A4_\uBB38\uC758_FAQ"
  '18': "intent_\uB370\uC774\uD130_\uC120\uBB3C_\uBAA9\uB85D_\uD655\uC778"
  '19': "intent_\uB370\uC774\uD130_\uC120\uBB3C_\uC694\uAE08\uC81C_\uBB38\uC758"
  '2': "intent_T\uBA64\uBC84\uC2ED_Gold_\uD61C\uD0DD_\uBB38\uC758_FAQ"
  '20': "intent_\uB370\uC774\uD130_\uC120\uBB3C\uD558\uAE30_\uBA40\uD2F0\uD134"
  '21': "intent_\uB370\uC774\uD130_\uC120\uBB3C\uD558\uAE30_\uBB38\uC758"
  '22': "intent_\uB370\uC774\uD130_\uC790\uB3D9_\uC120\uBB3C_\uBAA9\uB85D_\uD655\uC778"
  '23': "intent_\uB370\uC774\uD130_\uC790\uB3D9_\uC120\uBB3C\uD558\uAE30_\uBA40\uD2F0\
    \uD134"
  '24': "intent_\uB370\uC774\uD130_\uC790\uB3D9_\uC120\uBB3C\uD558\uAE30_\uBB38\uC758"
  '25': "intent_\uB370\uC774\uD130\uB85C\uBC0D\uBB34\uC870\uAC74\uCC28\uB2E8_\uAC00\
    \uC785"
  '26': "intent_\uB370\uC774\uD130\uC120\uBB3C\uD558\uAE30_\uB3C4\uC6C0\uB9D0_\uBB38\
    \uC758"
  '27': "intent_\uB85C\uBC0D_\uAC00\uC785_\uD655\uC778"
  '28': "intent_\uB85C\uBC0D_\uB3C4\uC6C0\uB9D0_\uBB38\uC758"
  '29': "intent_\uB85C\uBC0D_\uBD80\uAC00\uC11C\uBE44\uC2A4_\uAC00\uC785"
  '3': "intent_T\uBA64\uBC84\uC2ED_Silver_\uD61C\uD0DD_\uBB38\uC758_FAQ"
  '30': "intent_\uB85C\uBC0D_\uBD80\uAC00\uC11C\uBE44\uC2A4_\uBAA9\uB85D_\uD655\uC778"
  '31': "intent_\uB85C\uBC0D_\uBD80\uAC00\uC11C\uBE44\uC2A4_\uD574\uC9C0"
  '32': "intent_\uB85C\uBC0D_\uC694\uAE08\uC81C_\uAC00\uC785_\uBA40\uD2F0\uD134"
  '33': "intent_\uB85C\uBC0D_\uC694\uAE08\uC81C_\uBB38\uC758"
  '34': "intent_\uB85C\uBC0D_\uC694\uAE08\uC81C_\uCD94\uCC9C_\uBB38\uC758_\uBA40\uD2F0\
    \uD134"
  '35': "intent_\uB85C\uBC0D_\uC694\uAE08\uC81C_\uD574\uC9C0"
  '36': "intent_\uB85C\uBC0D_\uD604\uC9C0\uC2DC\uAC01\uC548\uB0B4\uC11C\uBE44\uC2A4\
    _\uAC00\uC785"
  '37': "intent_\uB85C\uBC0D\uC13C\uD130_\uC704\uCE58_\uBB38\uC758_\uBA40\uD2F0\uD134"
  '38': "intent_\uB85C\uBC0D\uC548\uB0B4\uBC29\uC1A1\uC11C\uBE44\uC2A4_\uAC00\uC785"
  '39': "intent_\uB9AC\uD544\uCFE0\uD3F0_\uB3C4\uC6C0\uB9D0_\uBB38\uC758"
  '4': "intent_T\uBA64\uBC84\uC2ED_VIP_PICK_\uD61C\uD0DD_\uBB38\uC758_FAQ"
  '40': "intent_\uB9AC\uD544\uCFE0\uD3F0_\uC0AC\uC6A9_\uBA40\uD2F0\uD134"
  '41': "intent_\uB9AC\uD544\uCFE0\uD3F0_\uC120\uBB3C_\uB0B4\uC5ED_\uC870\uD68C"
  '42': "intent_\uB9AC\uD544\uCFE0\uD3F0_\uC120\uBB3C\uD558\uAE30_\uBA40\uD2F0\uD134"
  '43': "intent_\uB9AC\uD544\uCFE0\uD3F0_\uC870\uD68C"
  '44': "intent_\uBA64\uBC84\uC2ED_\uB3C4\uC6C0\uB9D0_\uBB38\uC758"
  '45': "intent_\uBA64\uBC84\uC2ED_\uB4F1\uAE09_\uC870\uD68C"
  '46': "intent_\uBA64\uBC84\uC2ED_\uC2E0\uADDC_\uAC00\uC785"
  '47': "intent_\uBA64\uBC84\uC2ED_\uC7AC\uBC1C\uAE09"
  '48': "intent_\uBA64\uBC84\uC2ED_\uD61C\uD0DD_\uC870\uD68C"
  '49': "intent_\uBBF8\uB0A9\uC694\uAE08_\uB3C4\uC6C0\uB9D0_\uBB38\uC758"
  '5': "intent_T\uBA64\uBC84\uC2ED_VIP_\uB4F1\uAE09_\uAE30\uC900_\uBB38\uC758_FAQ"
  '50': "intent_\uBBF8\uB0A9\uC694\uAE08_\uC870\uD68C"
  '51': "intent_\uBBF8\uB798\uC2DC\uC810_\uC77C\uC2DC\uC815\uC9C0_\uD574\uC81C_FAQ"
  '52': "intent_\uBBF8\uC9C0\uC6D0"
  '53': "intent_\uBD80\uAC00\uC11C\uBE44\uC2A4_\uCD94\uCC9C_\uBB38\uC758"
  '54': "intent_\uC0C1\uB2F4_\uC2DC\uAC04_\uBB38\uC758_\uBA40\uD2F0\uD134"
  '55': "intent_\uC0C1\uB2F4\uC6D0_\uC5F0\uACB0_\uBB38\uC758_\uBA40\uD2F0\uD134"
  '56': "intent_\uC2E4\uC2DC\uAC04_\uB370\uC774\uD130_\uC794\uC5EC\uB7C9_\uD655\uC778"
  '57': "intent_\uC2E4\uC2DC\uAC04_\uB85C\uBC0D_\uC794\uC5EC\uB7C9_\uD655\uC778"
  '58': "intent_\uC2E4\uC2DC\uAC04_\uB85C\uBC0D\uC694\uAE08_\uC870\uD68C"
  '59': "intent_\uC2E4\uC2DC\uAC04_\uC0AC\uC6A9\uC694\uAE08_\uC870\uD68C"
  '6': "intent_T\uBA64\uBC84\uC2ED_VIP_\uC601\uD654_\uC608\uB9E4_\uBB38\uC758_FAQ"
  '60': "intent_\uC2E4\uC2DC\uAC04_\uC794\uC5EC\uB7C9_\uD655\uC778"
  '61': "intent_\uC2E4\uC2DC\uAC04_\uD1B5\uD654_\uC794\uC5EC\uB7C9_\uD655\uC778"
  '62': "intent_\uC2E4\uC2DC\uAC04\uC0AC\uC6A9\uB7C9_\uB3C4\uC6C0\uB9D0_\uBB38\uC758"
  '63': "intent_\uC694\uAE08_\uACC4\uC88C\uC774\uCCB4_\uB0A9\uBD80_\uBC29\uBC95_\uBB38\
    \uC758"
  '64': "intent_\uC694\uAE08_\uB0A9\uBD80_\uBC29\uBC95_\uBB38\uC758"
  '65': "intent_\uC694\uAE08_\uC740\uD589_\uB0A9\uBD80_\uBC29\uBC95_\uBB38\uC758"
  '66': "intent_\uC694\uAE08_\uCE74\uB4DC_\uB0A9\uBD80_\uBC29\uBC95_\uBB38\uC758"
  '67': "intent_\uC694\uAE08\uB0A9\uBD80_\uB3C4\uC6C0\uB9D0_\uBB38\uC758"
  '68': "intent_\uC694\uAE08\uC81C_\uCD94\uCC9C_\uBB38\uC758"
  '69': "intent_\uC694\uAE08\uC870\uD68C_\uB3C4\uC6C0\uB9D0_\uBB38\uC758"
  '7': "intent_T\uBA64\uBC84\uC2ED_VIP_\uC694\uAE08\uC81C_\uC774\uC6A9_\uBB38\uC758\
    _FAQ"
  '70': "intent_\uC6D4_\uAE30\uBCF8_\uC81C\uACF5\uB7C9_\uD655\uC778"
  '71': "intent_\uC6D4\uD3C9\uADE0_\uC0AC\uC6A9\uB7C9_\uD655\uC778"
  '72': "intent_\uC774\uBC88\uB2EC_\uB85C\uBC0D_\uCCAD\uAD6C\uC694\uAE08_\uC870\uD68C"
  '73': "intent_\uC774\uBC88\uB2EC_\uC18C\uC561\uACB0\uC81C\uC694\uAE08_\uC870\uD68C"
  '74': "intent_\uC774\uBC88\uB2EC_\uCCAD\uAD6C\uC694\uAE08_\uC870\uD68C"
  '75': "intent_\uC774\uBC88\uB2EC_\uCF58\uD150\uCE20\uC694\uAE08_\uC870\uD68C"
  '76': "intent_\uC77C\uC2DC\uC815\uC9C0_\uAE30\uAC04_\uD655\uC778"
  '77': "intent_\uC77C\uC2DC\uC815\uC9C0_\uB3C4\uC6C0\uB9D0_\uBB38\uC758"
  '78': "intent_\uC77C\uC2DC\uC815\uC9C0_\uBB38\uC758_\uBA40\uD2F0\uD134"
  '79': "intent_\uC77C\uC2DC\uC815\uC9C0_\uD574\uC81C"
  '8': "intent_T\uBA64\uBC84\uC2ED_VIP_\uC694\uAE08\uC81C\uBA85_\uBB38\uC758_FAQ"
  '80': "intent_\uC804\uD654_\uC0C1\uB2F4_\uC2DC\uAC04_\uBB38\uC758_\uBA40\uD2F0\uD134"
  '81': "intent_\uC804\uD654_\uC0C1\uB2F4\uC6D0_\uC5F0\uACB0_\uBB38\uC758_\uBA40\uD2F0\
    \uD134"
  '82': "intent_\uC9C0\uB09C\uB2EC_\uB85C\uBC0D_\uC0AC\uC6A9\uC694\uAE08_\uC870\uD68C"
  '83': "intent_\uC9C0\uB09C\uB2EC_\uB85C\uBC0D_\uCCAD\uAD6C\uC694\uAE08_\uC870\uD68C"
  '84': "intent_\uC9C0\uB09C\uB2EC_\uC0AC\uC6A9\uC694\uAE08_\uC870\uD68C"
  '85': "intent_\uC9C0\uB09C\uB2EC_\uC18C\uC561\uACB0\uC81C\uC694\uAE08_\uC870\uD68C"
  '86': "intent_\uC9C0\uB09C\uB2EC_\uCCAD\uAD6C\uC694\uAE08_\uC870\uD68C"
  '87': "intent_\uC9C0\uB09C\uB2EC_\uCF58\uD150\uCE20\uC694\uAE08_\uC870\uD68C"
  '88': "intent_\uC9C0\uC6D0_\uAE30\uB2A5_\uBB38\uC758"
  '9': "intent_T\uBA64\uBC84\uC2ED_VIP_\uD61C\uD0DD_\uBB38\uC758_FAQ"
intent_optimizer_lr: 3.0e-05
lower_text: true
max_epochs: 20
optimizer: AdamW
seq_len: 128
train_ratio: 0.8
